controller_list:
  - name: fake_knick_controller
    type: $(arg fake_execution_type)
    joints:
      - knick_joint1
      - knick_joint2
      - knick_joint3
      - knick_joint4
      - knick_joint5
      - knick_joint6
  - name: fake_scara_controller
    type: $(arg fake_execution_type)
    joints:
      - scara_joint_1
      - scara_joint_2
      - scara_joint_3
initial:  # Define initial robot poses per group
#  - group: knick
#    pose: home

  []