controller_list:
  - name: knick_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - knick_joint1
      - knick_joint2
      - knick_joint3
      - knick_joint4
      - knick_joint5
      - knick_joint6
  - name: scara_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - scara_joint_1
      - scara_joint_2
      - scara_joint_3
  - name: knick_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - knick_joint1
      - knick_joint2
      - knick_joint3
      - knick_joint4
      - knick_joint5
      - knick_joint6
  - name: scara_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - scara_joint_1
      - scara_joint_2
      - scara_joint_3